//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerClient.PokerServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfint", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfArrayOfPokerTableBLPWeT4Jje", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfArrayOfPokerTableBLPWeT4Jje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.PokerTableBL[] ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.PokerTableBL[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PokerTableBL", Namespace="http://schemas.datacontract.org/2004/07/PokerBL.Models")]
    [System.SerializableAttribute()]
    public partial class PokerTableBL : PokerClient.PokerServiceRef.PokerTable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasStartedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Move[] MovesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.PlayerBL[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PokerTableIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrTurn {
            get {
                return this.CurrTurnField;
            }
            set {
                if ((this.CurrTurnField.Equals(value) != true)) {
                    this.CurrTurnField = value;
                    this.RaisePropertyChanged("CurrTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasStarted {
            get {
                return this.HasStartedField;
            }
            set {
                if ((this.HasStartedField.Equals(value) != true)) {
                    this.HasStartedField = value;
                    this.RaisePropertyChanged("HasStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Move[] Moves {
            get {
                return this.MovesField;
            }
            set {
                if ((object.ReferenceEquals(this.MovesField, value) != true)) {
                    this.MovesField = value;
                    this.RaisePropertyChanged("Moves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPlayers {
            get {
                return this.NumOfPlayersField;
            }
            set {
                if ((this.NumOfPlayersField.Equals(value) != true)) {
                    this.NumOfPlayersField = value;
                    this.RaisePropertyChanged("NumOfPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.PlayerBL[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PokerTableId {
            get {
                return this.PokerTableIdField;
            }
            set {
                if ((this.PokerTableIdField.Equals(value) != true)) {
                    this.PokerTableIdField = value;
                    this.RaisePropertyChanged("PokerTableId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/PokerDL.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.Move))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.Player))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PlayerBL))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.BaseIdentityEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PokerTable))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PokerTableBL))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Move", Namespace="http://schemas.datacontract.org/2004/07/PokerDL.Models")]
    [System.SerializableAttribute()]
    public partial class Move : PokerClient.PokerServiceRef.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoveNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Operation OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PokerTableIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidAmount {
            get {
                return this.BidAmountField;
            }
            set {
                if ((this.BidAmountField.Equals(value) != true)) {
                    this.BidAmountField = value;
                    this.RaisePropertyChanged("BidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveNumber {
            get {
                return this.MoveNumberField;
            }
            set {
                if ((this.MoveNumberField.Equals(value) != true)) {
                    this.MoveNumberField = value;
                    this.RaisePropertyChanged("MoveNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Operation Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((this.OperationField.Equals(value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PokerTableId {
            get {
                return this.PokerTableIdField;
            }
            set {
                if ((this.PokerTableIdField.Equals(value) != true)) {
                    this.PokerTableIdField = value;
                    this.RaisePropertyChanged("PokerTableId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/PokerBL.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PlayerBL))]
    public partial class Player : PokerClient.PokerServiceRef.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChipsOnTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PokerTableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondCardField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChipsOnTable {
            get {
                return this.ChipsOnTableField;
            }
            set {
                if ((this.ChipsOnTableField.Equals(value) != true)) {
                    this.ChipsOnTableField = value;
                    this.RaisePropertyChanged("ChipsOnTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstCard {
            get {
                return this.FirstCardField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstCardField, value) != true)) {
                    this.FirstCardField = value;
                    this.RaisePropertyChanged("FirstCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PokerTableId {
            get {
                return this.PokerTableIdField;
            }
            set {
                if ((this.PokerTableIdField.Equals(value) != true)) {
                    this.PokerTableIdField = value;
                    this.RaisePropertyChanged("PokerTableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondCard {
            get {
                return this.SecondCardField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondCardField, value) != true)) {
                    this.SecondCardField = value;
                    this.RaisePropertyChanged("SecondCard");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerBL", Namespace="http://schemas.datacontract.org/2004/07/PokerBL.Models")]
    [System.SerializableAttribute()]
    public partial class PlayerBL : PokerClient.PokerServiceRef.Player {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseIdentityEntity", Namespace="http://schemas.datacontract.org/2004/07/PokerDL.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PokerTable))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PokerTableBL))]
    public partial class BaseIdentityEntity : PokerClient.PokerServiceRef.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PokerTable", Namespace="http://schemas.datacontract.org/2004/07/PokerBL.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PokerClient.PokerServiceRef.PokerTableBL))]
    public partial class PokerTable : PokerClient.PokerServiceRef.BaseIdentityEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FifthCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FourthCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinBetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player1IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player2IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player3IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player4IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player5IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PokerTableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TablePotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThirdCardField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerId {
            get {
                return this.DealerIdField;
            }
            set {
                if ((this.DealerIdField.Equals(value) != true)) {
                    this.DealerIdField = value;
                    this.RaisePropertyChanged("DealerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FifthCard {
            get {
                return this.FifthCardField;
            }
            set {
                if ((object.ReferenceEquals(this.FifthCardField, value) != true)) {
                    this.FifthCardField = value;
                    this.RaisePropertyChanged("FifthCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstCard {
            get {
                return this.FirstCardField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstCardField, value) != true)) {
                    this.FirstCardField = value;
                    this.RaisePropertyChanged("FirstCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FourthCard {
            get {
                return this.FourthCardField;
            }
            set {
                if ((object.ReferenceEquals(this.FourthCardField, value) != true)) {
                    this.FourthCardField = value;
                    this.RaisePropertyChanged("FourthCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinBet {
            get {
                return this.MinBetField;
            }
            set {
                if ((this.MinBetField.Equals(value) != true)) {
                    this.MinBetField = value;
                    this.RaisePropertyChanged("MinBet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player1Id {
            get {
                return this.Player1IdField;
            }
            set {
                if ((this.Player1IdField.Equals(value) != true)) {
                    this.Player1IdField = value;
                    this.RaisePropertyChanged("Player1Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player2Id {
            get {
                return this.Player2IdField;
            }
            set {
                if ((this.Player2IdField.Equals(value) != true)) {
                    this.Player2IdField = value;
                    this.RaisePropertyChanged("Player2Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player3Id {
            get {
                return this.Player3IdField;
            }
            set {
                if ((this.Player3IdField.Equals(value) != true)) {
                    this.Player3IdField = value;
                    this.RaisePropertyChanged("Player3Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player4Id {
            get {
                return this.Player4IdField;
            }
            set {
                if ((this.Player4IdField.Equals(value) != true)) {
                    this.Player4IdField = value;
                    this.RaisePropertyChanged("Player4Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player5Id {
            get {
                return this.Player5IdField;
            }
            set {
                if ((this.Player5IdField.Equals(value) != true)) {
                    this.Player5IdField = value;
                    this.RaisePropertyChanged("Player5Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PokerTableName {
            get {
                return this.PokerTableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PokerTableNameField, value) != true)) {
                    this.PokerTableNameField = value;
                    this.RaisePropertyChanged("PokerTableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondCard {
            get {
                return this.SecondCardField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondCardField, value) != true)) {
                    this.SecondCardField = value;
                    this.RaisePropertyChanged("SecondCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TablePot {
            get {
                return this.TablePotField;
            }
            set {
                if ((this.TablePotField.Equals(value) != true)) {
                    this.TablePotField = value;
                    this.RaisePropertyChanged("TablePot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdCard {
            get {
                return this.ThirdCardField;
            }
            set {
                if ((object.ReferenceEquals(this.ThirdCardField, value) != true)) {
                    this.ThirdCardField = value;
                    this.RaisePropertyChanged("ThirdCard");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/PokerDL.Models")]
    public enum Operation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Call = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Raise = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fold = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Check = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllIn = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfPokerTableBLPWeT4Jje", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfPokerTableBLPWeT4Jje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.PokerTableBL ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.PokerTableBL Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfStartGameStatusPWeT4Jje", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfStartGameStatusPWeT4Jje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.StartGameStatus ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.StartGameStatus Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartGameStatus", Namespace="http://schemas.datacontract.org/2004/07/PokerBL.Models")]
    [System.SerializableAttribute()]
    public partial class StartGameStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Move BigBlindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Card PlayerCard1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Card PlayerCard2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Move SmallBlindField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Move BigBlind {
            get {
                return this.BigBlindField;
            }
            set {
                if ((object.ReferenceEquals(this.BigBlindField, value) != true)) {
                    this.BigBlindField = value;
                    this.RaisePropertyChanged("BigBlind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerId {
            get {
                return this.DealerIdField;
            }
            set {
                if ((this.DealerIdField.Equals(value) != true)) {
                    this.DealerIdField = value;
                    this.RaisePropertyChanged("DealerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Card PlayerCard1 {
            get {
                return this.PlayerCard1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerCard1Field, value) != true)) {
                    this.PlayerCard1Field = value;
                    this.RaisePropertyChanged("PlayerCard1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Card PlayerCard2 {
            get {
                return this.PlayerCard2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerCard2Field, value) != true)) {
                    this.PlayerCard2Field = value;
                    this.RaisePropertyChanged("PlayerCard2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Move SmallBlind {
            get {
                return this.SmallBlindField;
            }
            set {
                if ((object.ReferenceEquals(this.SmallBlindField, value) != true)) {
                    this.SmallBlindField = value;
                    this.RaisePropertyChanged("SmallBlind");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/PokerDL.Models")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Face {
            get {
                return this.FaceField;
            }
            set {
                if ((object.ReferenceEquals(this.FaceField, value) != true)) {
                    this.FaceField = value;
                    this.RaisePropertyChanged("Face");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suit {
            get {
                return this.SuitField;
            }
            set {
                if ((object.ReferenceEquals(this.SuitField, value) != true)) {
                    this.SuitField = value;
                    this.RaisePropertyChanged("Suit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfTableStatusPWeT4Jje", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfTableStatusPWeT4Jje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.TableStatus ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.TableStatus Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableStatus", Namespace="http://schemas.datacontract.org/2004/07/PokerBL.Models")]
    [System.SerializableAttribute()]
    public partial class TableStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasGameFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMyTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Move LastMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.Card[] TableCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] WinnerIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasGameFinished {
            get {
                return this.HasGameFinishedField;
            }
            set {
                if ((this.HasGameFinishedField.Equals(value) != true)) {
                    this.HasGameFinishedField = value;
                    this.RaisePropertyChanged("HasGameFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMyTurn {
            get {
                return this.IsMyTurnField;
            }
            set {
                if ((this.IsMyTurnField.Equals(value) != true)) {
                    this.IsMyTurnField = value;
                    this.RaisePropertyChanged("IsMyTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Move LastMove {
            get {
                return this.LastMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.LastMoveField, value) != true)) {
                    this.LastMoveField = value;
                    this.RaisePropertyChanged("LastMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.Card[] TableCards {
            get {
                return this.TableCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.TableCardsField, value) != true)) {
                    this.TableCardsField = value;
                    this.RaisePropertyChanged("TableCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] WinnerIds {
            get {
                return this.WinnerIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerIdsField, value) != true)) {
                    this.WinnerIdsField = value;
                    this.RaisePropertyChanged("WinnerIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfArrayOfPlayerBLPWeT4Jje", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfArrayOfPlayerBLPWeT4Jje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.PlayerBL[] ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.PlayerBL[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResponseOfArrayOfPokerTablePWeT4Jje", Namespace="http://schemas.datacontract.org/2004/07/PokerService")]
    [System.SerializableAttribute()]
    public partial class ServerResponseOfArrayOfPokerTablePWeT4Jje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PokerClient.PokerServiceRef.PokerTable[] ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PokerClient.PokerServiceRef.PokerTable[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PokerServiceRef.IPokerService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IPokerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/SignUp", ReplyAction="http://tempuri.org/IPokerService/SignUpResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfint SignUp(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/SignUp", ReplyAction="http://tempuri.org/IPokerService/SignUpResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfint> SignUpAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/Login", ReplyAction="http://tempuri.org/IPokerService/LoginResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfint Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/Login", ReplyAction="http://tempuri.org/IPokerService/LoginResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfint> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/Logout", ReplyAction="http://tempuri.org/IPokerService/LogoutResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfboolean Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/Logout", ReplyAction="http://tempuri.org/IPokerService/LogoutResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetExistingTables", ReplyAction="http://tempuri.org/IPokerService/GetExistingTablesResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTableBLPWeT4Jje GetExistingTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetExistingTables", ReplyAction="http://tempuri.org/IPokerService/GetExistingTablesResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTableBLPWeT4Jje> GetExistingTablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/CreateTable", ReplyAction="http://tempuri.org/IPokerService/CreateTableResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje CreateTable(string PokerTableName, int NumOfPlayers, int MinBetAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/CreateTable", ReplyAction="http://tempuri.org/IPokerService/CreateTableResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje> CreateTableAsync(string PokerTableName, int NumOfPlayers, int MinBetAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/LeaveTable", ReplyAction="http://tempuri.org/IPokerService/LeaveTableResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfboolean LeaveTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/LeaveTable", ReplyAction="http://tempuri.org/IPokerService/LeaveTableResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> LeaveTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/JoinTable", ReplyAction="http://tempuri.org/IPokerService/JoinTableResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje JoinTable(int TableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/JoinTable", ReplyAction="http://tempuri.org/IPokerService/JoinTableResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje> JoinTableAsync(int TableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/StartGame", ReplyAction="http://tempuri.org/IPokerService/StartGameResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfStartGameStatusPWeT4Jje StartGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/StartGame", ReplyAction="http://tempuri.org/IPokerService/StartGameResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfStartGameStatusPWeT4Jje> StartGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/HasGameStarted", ReplyAction="http://tempuri.org/IPokerService/HasGameStartedResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfboolean HasGameStarted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/HasGameStarted", ReplyAction="http://tempuri.org/IPokerService/HasGameStartedResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> HasGameStartedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetTableStatus", ReplyAction="http://tempuri.org/IPokerService/GetTableStatusResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfTableStatusPWeT4Jje GetTableStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetTableStatus", ReplyAction="http://tempuri.org/IPokerService/GetTableStatusResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfTableStatusPWeT4Jje> GetTableStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/ExecuteMove", ReplyAction="http://tempuri.org/IPokerService/ExecuteMoveResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfboolean ExecuteMove(PokerClient.PokerServiceRef.Operation Operation, int BidAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/ExecuteMove", ReplyAction="http://tempuri.org/IPokerService/ExecuteMoveResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> ExecuteMoveAsync(PokerClient.PokerServiceRef.Operation Operation, int BidAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/UpdatePlayers", ReplyAction="http://tempuri.org/IPokerService/UpdatePlayersResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfArrayOfPlayerBLPWeT4Jje UpdatePlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/UpdatePlayers", ReplyAction="http://tempuri.org/IPokerService/UpdatePlayersResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfArrayOfPlayerBLPWeT4Jje> UpdatePlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetWallet", ReplyAction="http://tempuri.org/IPokerService/GetWalletResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfint GetWallet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetWallet", ReplyAction="http://tempuri.org/IPokerService/GetWalletResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfint> GetWalletAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetHistoryTables", ReplyAction="http://tempuri.org/IPokerService/GetHistoryTablesResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTablePWeT4Jje GetHistoryTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetHistoryTables", ReplyAction="http://tempuri.org/IPokerService/GetHistoryTablesResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTablePWeT4Jje> GetHistoryTablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/InitHistoryMoves", ReplyAction="http://tempuri.org/IPokerService/InitHistoryMovesResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfboolean InitHistoryMoves(int TableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/InitHistoryMoves", ReplyAction="http://tempuri.org/IPokerService/InitHistoryMovesResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> InitHistoryMovesAsync(int TableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/ExecuteHistoryMove", ReplyAction="http://tempuri.org/IPokerService/ExecuteHistoryMoveResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfboolean ExecuteHistoryMove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/ExecuteHistoryMove", ReplyAction="http://tempuri.org/IPokerService/ExecuteHistoryMoveResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> ExecuteHistoryMoveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetTableByHistory", ReplyAction="http://tempuri.org/IPokerService/GetTableByHistoryResponse")]
        PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje GetTableByHistory(PokerClient.PokerServiceRef.PokerTable replayTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerService/GetTableByHistory", ReplyAction="http://tempuri.org/IPokerService/GetTableByHistoryResponse")]
        System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje> GetTableByHistoryAsync(PokerClient.PokerServiceRef.PokerTable replayTable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPokerServiceChannel : PokerClient.PokerServiceRef.IPokerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PokerServiceClient : System.ServiceModel.ClientBase<PokerClient.PokerServiceRef.IPokerService>, PokerClient.PokerServiceRef.IPokerService {
        
        public PokerServiceClient() {
        }
        
        public PokerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PokerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfint SignUp(string username, string password) {
            return base.Channel.SignUp(username, password);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfint> SignUpAsync(string username, string password) {
            return base.Channel.SignUpAsync(username, password);
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfint Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfint> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfboolean Logout() {
            return base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTableBLPWeT4Jje GetExistingTables() {
            return base.Channel.GetExistingTables();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTableBLPWeT4Jje> GetExistingTablesAsync() {
            return base.Channel.GetExistingTablesAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje CreateTable(string PokerTableName, int NumOfPlayers, int MinBetAmount) {
            return base.Channel.CreateTable(PokerTableName, NumOfPlayers, MinBetAmount);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje> CreateTableAsync(string PokerTableName, int NumOfPlayers, int MinBetAmount) {
            return base.Channel.CreateTableAsync(PokerTableName, NumOfPlayers, MinBetAmount);
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfboolean LeaveTable() {
            return base.Channel.LeaveTable();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> LeaveTableAsync() {
            return base.Channel.LeaveTableAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje JoinTable(int TableId) {
            return base.Channel.JoinTable(TableId);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje> JoinTableAsync(int TableId) {
            return base.Channel.JoinTableAsync(TableId);
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfStartGameStatusPWeT4Jje StartGame() {
            return base.Channel.StartGame();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfStartGameStatusPWeT4Jje> StartGameAsync() {
            return base.Channel.StartGameAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfboolean HasGameStarted() {
            return base.Channel.HasGameStarted();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> HasGameStartedAsync() {
            return base.Channel.HasGameStartedAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfTableStatusPWeT4Jje GetTableStatus() {
            return base.Channel.GetTableStatus();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfTableStatusPWeT4Jje> GetTableStatusAsync() {
            return base.Channel.GetTableStatusAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfboolean ExecuteMove(PokerClient.PokerServiceRef.Operation Operation, int BidAmount) {
            return base.Channel.ExecuteMove(Operation, BidAmount);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> ExecuteMoveAsync(PokerClient.PokerServiceRef.Operation Operation, int BidAmount) {
            return base.Channel.ExecuteMoveAsync(Operation, BidAmount);
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfArrayOfPlayerBLPWeT4Jje UpdatePlayers() {
            return base.Channel.UpdatePlayers();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfArrayOfPlayerBLPWeT4Jje> UpdatePlayersAsync() {
            return base.Channel.UpdatePlayersAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfint GetWallet() {
            return base.Channel.GetWallet();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfint> GetWalletAsync() {
            return base.Channel.GetWalletAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTablePWeT4Jje GetHistoryTables() {
            return base.Channel.GetHistoryTables();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfArrayOfPokerTablePWeT4Jje> GetHistoryTablesAsync() {
            return base.Channel.GetHistoryTablesAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfboolean InitHistoryMoves(int TableId) {
            return base.Channel.InitHistoryMoves(TableId);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> InitHistoryMovesAsync(int TableId) {
            return base.Channel.InitHistoryMovesAsync(TableId);
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfboolean ExecuteHistoryMove() {
            return base.Channel.ExecuteHistoryMove();
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfboolean> ExecuteHistoryMoveAsync() {
            return base.Channel.ExecuteHistoryMoveAsync();
        }
        
        public PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje GetTableByHistory(PokerClient.PokerServiceRef.PokerTable replayTable) {
            return base.Channel.GetTableByHistory(replayTable);
        }
        
        public System.Threading.Tasks.Task<PokerClient.PokerServiceRef.ServerResponseOfPokerTableBLPWeT4Jje> GetTableByHistoryAsync(PokerClient.PokerServiceRef.PokerTable replayTable) {
            return base.Channel.GetTableByHistoryAsync(replayTable);
        }
    }
}
